runs:
  using: "composite"
  steps:
    - name: Create manifest for install Wazuh stack
      shell: bash
      run: |
        hostname=$(sudo puppetserver ca list --all | awk '{if(NR>1)print $1;}'| sed 's/[.]$//')
        sudo echo "\$discovery_type = 'single-node'" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage { 'certificates': }" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage { 'repo': }" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage { 'indexerdeploy': }" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage { 'securityadmin': }" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage { 'dashboard': }" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage { 'manager': }" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "Stage[certificates] -> Stage[repo] -> Stage[indexerdeploy] -> Stage[securityadmin] -> Stage[manager] -> Stage[dashboard]" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "Exec {" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "timeout => 0," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "node "\"$hostname\"" {" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp  > /dev/null
        sudo echo "class { 'wazuh::certificates':" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  indexer_certs => [['node-1','127.0.0.1']]," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  manager_certs => [['master','127.0.0.1']]," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  dashboard_certs => ['127.0.0.1']," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  stage => certificates," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "class { 'wazuh::repo':" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage => repo," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "class { 'wazuh::indexer':" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  stage => indexerdeploy," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "class { 'wazuh::securityadmin':" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "stage => securityadmin" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "class { 'wazuh::manager':" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  stage => manager," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "class { 'wazuh::filebeat_oss':" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  stage => manager," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "class { 'wazuh::dashboard':" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "  stage => dashboard," | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo cat /etc/puppetlabs/code/environments/production/manifests/stack.pp

    - name: Create manifest for install Wazuh stack
      shell: bash
      run: |
        sudo sed -i 's/packages.wazuh.com/packages-dev.wazuh.com/g' /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/certificates.pp
        sudo sed -i 's/packages.wazuh.com\/4.x/packages-dev.wazuh.com\/pre-release/g' /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/filebeat_oss.pp
        sudo sed -i 's/v4.8.0/4.8.0/g' /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/filebeat_oss.pp
        sudo sed -i 's/packages.wazuh.com\/4.x/packages-dev.wazuh.com\/pre-release/g' /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/params_agent.pp
        sudo sed -i 's/packages.wazuh.com\/4.x/packages-dev.wazuh.com\/pre-release/g' /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/repo.pp
        sudo sed -i 's/packages.wazuh.com\/key/packages-dev.wazuh.com\/key/g' /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/repo.pp
        sudo sed -i "s/'stable'/'unstable'/g" /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/repo.pp
        echo "certificates.pp"
        sudo cat /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/certificates.pp
        echo "filebeat_oss.pp"
        sudo cat /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/filebeat_oss.pp
        echo "repo.pp"
        sudo cat /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/repo.pp

    - name: Install Wazuh Stack
      shell: bash
      run: sudo bash -c 'puppet agent -tod || test $? -eq 2'

